services:
  - type: web
    name: buses-tmb
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TMB_APP_ID
        value: 91bd6b08
      - key: TMB_APP_KEY
        value: 44c70cf7f4fd3c6c86c6c634b3cac625
      - key: RENDER_API_KEY
        value: rnd_gfxPGUiTPozK13CJ71KqfgC7MGQ4
